### ISSUE TITLE
Link to a live demo?

### ISSUE THREAD

**Issue by impressivewebs** [aullah/quickmenu#1]
I don't see a link to a demo page for this that I can try out. Are you able to add one?

**Comment by aullah** [comment]
Hi Louis,

Thank you for raising this. I've had others asking for a demo too, therefore due to the requests (including yours) I will have one made available later this week.

I will keep you posted. Thanks again. 👍

**Comment by aullah** [comment]
Hello there,

A live demo for this project has been created and the README.md has been updated to reflect this. You can access the live demo at [QuickMenu.org](https://quickmenu.org). On desktop you will see inline navigational links, whereas on a mobile device (mobile or tablet) you will see the Quick Menu.

The demo page at the moment is a basic example, the page has no content other than the navigation links. However whenever I am able to spare some time, I will enhance the page with content to provide a better representation of the Quick Menu in use on a site.

All the best,
Arif.

**Comment by impressivewebs** [comment]
Looks great! Works nicely on my iPhone! I'll be sure to share the tool in my newsletter: https://webtoolsweekly.com/

**Comment by aullah** [comment]
That sounds brilliant and it is much greatly appreciated. Thank you also for your contribution to improving this project. 😊
